### ISSUE TITLE
正しいライセンスはどちら？

### ISSUE THREAD

**Issue by miminashi** [panicjp/kicad-jp-library#1]
https://github.com/panicjp/kicad-jp-library/blob/master/README.md#license

README.md本文中には CC-BY-SA との記載がありますが、バナーが CC-BY-NC-SA になっています。
どちらが正しいライセンスでしょう？

**Comment by panicjp** [comment]
あらま。
バナーが間違いです。CC-BY-SAを意図していました。
とはいえ、特にこだわりがあるわけでは無いので、もっとふさわしいライセンスとかありましたら教えてくださいませ(_ _),
